/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "main.h"

void MyLine(cv::Mat img, cv::Point start, cv::Point end ) {
	int thickness = 2;
	int lineType = cv::LINE_8;
	line(img,
		start,
		end,
		cv::Scalar( 0, 0, 0 ),
		thickness,
		lineType );
}

int main(int argc, char const *argv[]) {
	std::cout << "Sim Start" << std::endl;


	cv::Mat image = cv::Mat::zeros(400, 400, CV_8UC3);


	MyLine(image, {0,0}, {100,100});
	
	cv::waitKey(100);
	while (true) {
		cv::imshow("Sim Window", image);
		cv::waitKey(30);
	}

	std::cout << "Program end" << std::endl;

	return 0;
}
